#!/bin/bash

file=links.txt
until [[ -z $(grep '[^[:space:]]' $file) ]]
do
	if (( $(df | grep /dev/ploop | awk '{sub (/%/, "", $5); print $5 }') < 80 ))
	then
		proxychains4 python3 /home/plexuser/server-scripts/aria-dl.py $file
		echo
		echo "RESTARTING..."
		echo
	else
		echo
		echo "STORAGE FULL"
		echo
		exit
	fi
done

echo
echo "COMPLETE"
echo
