#!/bin/bash

file=links.txt
until [[ -z $(grep '[^[:space:]]' $file) ]]
do
	if (( $(df | grep /dev/ploop | awk '{sub (/%/, "", $5); print $5 }') < 80 ))
	then
		proxychains4 python3 /home/plexuser/server-scripts/aria-dl.py $file
		echo
		echo "RESTARTING..."
		echo
	else
		echo
		echo "STORAGE FULL, ORGANISING AND UPLOADING"
		echo
		mkdir -p /home/plexuser/uploads/Movies
		mv download/* /home/plexuser/uploads/Movies/
		plex-upload
	fi
done

echo
echo "FINISHED DOWNLOADING, ORGANISING AND UPLOADING"
echo
mkdir -p /home/plexuser/uploads/Movies
mv download/* /home/plexuser/uploads/Movies/
plex-upload

echo
echo "COMPLETE"
echo
