#!/bin/bash
# java 8
# patched filebot 4.7.9

DST=~/uploads
FORMAT="{plex.path.ascii()}"
LOGFILE=~/logs/filebot.log
MODE="Rename -non-strict"
#MODE=interactive

filebot -rename * --output $DST --format $FORMAT --log-file $LOGFILE --mode $MODE -no-xattr

