#!/bin/bash
# java 8
# patched filebot 4.7.9

DST=~/uploads
FORMAT="{plex.path.ascii()}"
#FORMAT="{plex.path.ascii()}.x264"
LOGFILE=~/logs/filebot.log
MODE="Rename -non-strict"
#MODE=interactive

echo $@
filebot -rename * --output $DST --format $FORMAT --log-file $LOGFILE --mode $MODE -no-xattr #--q "Hunter x Hunter 2011"

echo .
echo .
echo "Remember to make a file.txt!"
echo .
echo .
